-- Creating the main transaction table 
CREATE TABLE dbo.Transactions(
	TransactionID int NOT NULL,
	OrderNumber int NOT NULL,
	LineItem tinyint NOT NULL,
	OrderDate date NOT NULL,
	DeliveryDate date NULL,
	Quantity tinyint NOT NULL,
	CustomerID int NOT NULL,
	CustomerGender nvarchar(50) NOT NULL,
	CustomerName nvarchar(50) NOT NULL,
	CustomerCity nvarchar(50) NOT NULL,
	CustomerStateCode nvarchar(50) NOT NULL,
	CustomerState nvarchar(50) NOT NULL,
	CustomerZip nvarchar(50) NOT NULL,
	CustomerCountry nvarchar(50) NOT NULL,
	CustomerContinent nvarchar(50) NOT NULL,
	CustomerDOB date NOT NULL,
	StoreID tinyint NOT NULL,
	StoreCountry nvarchar(50) NOT NULL,
	StoreState nvarchar(50) NOT NULL,
	StoreSqMeters smallint NOT NULL,
	StoreOpenDate date NOT NULL,
	ProductID smallint NOT NULL,
	ProductName nvarchar(100) NOT NULL,
	ProductBrand nvarchar(50) NOT NULL,
	ProductColor nvarchar(50) NOT NULL,
	ProductCost money NOT NULL,
	ProductPrice money NOT NULL,
	ProductSubcategoryID time(7) NOT NULL,
	ProductSubcategory nvarchar(50) NOT NULL,
	ProductCategoryID tinyint NOT NULL,
	ProductCategory nvarchar(50) NOT NULL
)